# Generated by Django 4.2.7 on 2026-01-03 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0003_donor_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationschedule',
            name='preferred_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_donations', to='blood_donation.hospital'),
        ),
    ]
