# Generated by Django 4.2.7 on 2026-01-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0004_donationschedule_preferred_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
    ]
